global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'test-metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          environment: 'testing'
          
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']