name: CI - Tests avec Allure et Monitoring

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Send_allure_Report_Node_js_25_x:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        cache: 'pip'

    - name: Install allure
      run: npm install -g allure-commandline

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        

    - name: Use Node.js 25.x
      uses: actions/setup-node@v4
      with:
        node-version: 25.x

    - name : install Allure CLI
      run: |
       npm install -g allure-commandline
       allure --version

    - name : Execute tests with Allure reporting
      run: |
        pytest tests/ -v --alluredir=reports
      continue-on-error: true

    - name: Generate Allure report
      if: always()
      run: allure generate reports --clean -o allure-report


    - name: Upload Allure report artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: reports/
        retention-days: 30
    - name: Upload Allure HTML report artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-html-report
        path: allure-report/
        retention-days: 30