name: CI - Tests avec Allure et Monitoring

on:
  push:
    branches: [ main ]  # Quelles branches ?
  pull_request:
    branches: [ main ]  # Vers quelle branche ?

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        node-version: [25.x]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install allure
      run: npm install -g allure-commandline
    - name: Install Python dependencies
      run: python -m venv venv
    - name: Install Node.js dependencies
      run: npm install
    - name: Run tests with monitoring
      run: |
        source venv/bin/activate  # Windows: venv\Scripts\activate
        npm run test:monitoring
    - name: Generate Allure report
      run: |
        allure generate ./allure-results --clean -o ./allure-report
    - name: Upload Allure report artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report-${{ matrix['node-version'] }}
        path: ./allure-report